import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Sidebar from "../components/Layout/sidebar";
import Header from "../components/Layout/header";
// import { ThemeProvider } from "@/context/themeContext";
import { Providers } from "@/context/themeProvider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Real Estate Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <Sidebar />

          {/* Header fixo */}
          <div className="fixed top-0 right-0 w-full z-50 ">
            <Header />
          </div>
          {/* Conteúdo principal */}
          <div className="lg:ml-64">
            {/* Conteúdo abaixo do header */}
            <main className="pt-16 lg:pt-20 p-8 min-h-screen bg-[var(--background-color)] dark:bg-[var(--background-color)]">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
